In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("../data/Advertising.csv", index_col=0)
df

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [5]:
number_of_samples, number_of_features = (df.shape[0], df.shape[1]-1) #-1 because Sales is label and not a feature

number_of_samples, number_of_features

# Vi har 200 samples och 3 features, vi tog bort sales eftersom det inte är en feater
# Label = namn eller nummer för raden

(200, 3)

In [10]:
X, y = df.drop("Sales", axis="columns"), df["Sales"]
X.head()

TV  Radio  Newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [8]:
y.head()

1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: Sales, dtype: float64

# SKlearn - typical steps

1. train|test split, sometimes train|val|test split
2. scaling sometimes required
    - min-max scaling
    - standardiztion
    - ...
    - scale the training data,
    - scale test data to the training data --> avoiding data leakage
3. Fit algorithm to training data - model training
4. Predict test data
5. Evaluate


# Train|test split

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((140, 3), (60, 3), (140,), (60,))

## Feature scaling

Normalization (min-max feature scaling)
- $X' = \frac{X-X_{\min}}{X_{max}-X_{min}}$

Feature standardization
- $X' = \frac{X-\mu}{\sigma}$

In [15]:
from sklearn.preprocessing import MinMaxScaler

# Instantiate a scaler instance
scaler = MinMaxScaler()
scaler.fit(X_train) # IMPORTANT - use this for training data

scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min()=}")
print(f"{scaled_X_train.max()=}")
print(f"{scaled_X_test.min()=}")
print(f"{scaled_X_test.max()=}")
# note scaled_X_test.min != 0, scaled_X_test.max != 1
# 0 <= scaled_X_train <=1
# 0.005964214711729622 <= scaled_X_test <= 1.1302186878727631

scaled_X_train.min()=0.0
scaled_X_train.max()=1.0
scaled_X_test.min()=0.005964214711729622
scaled_X_test.max()=1.1302186878727631


In [18]:
scaled_X_train.shape, scaled_X_test.shape

((140, 3), (60, 3))

# Linear regression

In [20]:
from sklearn.linear_model import LinearRegression

model_OLS = LinearRegression()
model_OLS.fit(scaled_X_train, y_train) # fit on training data
print(f"Parameters {model_OLS.coef_}") # Beta 1, beta2 & beta 3
print(f"Intercept {model_OLS.intercept_}") # Beta 0 - intercept
# Får inte predicta på oskalad data
# Ju fler transformationer man gör desto svårare blir det att tolka datan

Parameters [13.02832938  9.88465985  0.69237469]
Intercept 2.7418553248528124


# Stochastic gradient descent

In [21]:
from sklearn.linear_model import SGDRegressor

model_SGD = SGDRegressor(loss="squared_error", max_iter=1000)
model_SGD.fit(scaled_X_train, y_train)

print(f"Parameters {model_SGD.coef_}") # Beta 1, beta2 & beta 3
print(f"Intercept {model_SGD.intercept_}") # Beta 0 - intercept

Parameters [11.99448145  9.01812081  1.34217034]
Intercept [3.55172037]


# Manual prediction

In [25]:
test_sample_features = scaled_X_test[0].reshape(1, -1) # ändrar dimensionerna på arrayen
test_sample_label = y_test.values[0]
test_sample_features, test_sample_label

(array([[0.54988164, 0.63709677, 0.52286282]]), 16.9)

In [27]:
model_OLS.predict(test_sample_features)

array([16.5653963])

In [28]:
X_test.iloc[0].to_numpy()

array([163.3,  31.6,  52.9])

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 1. predict on test data
y_pred_OLS = model_OLS.predict(scaled_X_test)
y_pred_SGD = model_SGD.predict(scaled_X_test)
y_pred_OLS[:5]

array([16.5653963 , 21.18822792, 21.55107058, 10.88923816, 22.20231988])

In [32]:
y_pred_SGD[:5]

array([16.59445211, 20.82377759, 21.12200796, 11.30599922, 21.40707835])

In [33]:
y_test[:5].values

array([16.9, 22.4, 21.4,  7.3, 24.7])

In [35]:
mae_OLS = mean_absolute_error(y_test, y_pred_OLS)
mae_SGD = mean_absolute_error(y_test, y_pred_SGD)

mse_OLS = mean_squared_error(y_test, y_pred_OLS)
mse_SGD = mean_squared_error(y_test, y_pred_SGD)

rmse_OLS = np.sqrt(mse_OLS)
rmse_SGD = np.sqrt(mse_SGD)

print(f"{mae_OLS=:.4f} \t {mse_OLS=:.4f} \t {rmse_OLS=:.4f}")
print(f"{mae_SGD=:.4f} \t {mse_SGD=:.4f} \t {rmse_SGD=:.4f}")

mae_OLS=1.5117 	 mse_OLS=3.7968 	 rmse_OLS=1.9485
mae_SGD=1.5222 	 mse_SGD=4.0771 	 rmse_SGD=2.0192
